---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cobalt-default
spec:
  destination:
    name: cobalt
  precedence: 4
  route:
  - labels:
      version: green
    weight: 100
