---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cobalt-default
spec:
  destination:
    name: cobalt
  precedence: 1
  route:
  - labels:
      version: blue
    weight: 100
