---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cobalt-green
spec:
  destination:
    name: cobalt
  precedence: 2
  match:
    request:
      headers:
        user:
          regex: "gokulpch"
  route:
  - labels:
      version: green
